# Only change it if you know how to manually upgrade the configuration file
version: 1

# Currently available: "en_US", "zh_CN"
language: "en_US"

# Use Minecraft's default spawn point instead of the plugin's
useMinecraftSpawnPoint: false

# Wait to use /spawn again
cooldown:
  # Seconds. A value <1 means disabled
  sec: 60

# Wait before teleporting
warmup:
  # Seconds. A value <1 means disabled
  sec: 5
  # When the listed things happen, cancel the pending teleportation
  # Set the value of an event to false to prevent the plugin from checking it
  interruptBy:
    move: true
    message: true
    interact: true
    damage: true
