name: Spawn
version: '${project.version}'
description: Teleport to server spawn point
authors: [ MCUmbrella ]
website: https://github.com/MSUPlugins/Spawn
main: vip.floatationdevice.msu.spawn.Spawn
api-version: 1.13
depend:
  - MSUCore
commands:
  spawn:
    description: "Teleport to spawn point"
  setspawn:
    description: "Set spawn point"
permissions:
  spawn.spawn:
    description: "Allows the player to teleport to spawn point"
    default: true
  spawn.setspawn:
    description: "Allows the player to set the spawn point"
    default: op
  spawn.nocooldown:
    description: "Allows the player to bypass the cooldown"
    default: op
  spawn.nowarmup:
    description: "Allows the player to bypass the warmup"
    default: op
